name: terminal_view
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  lxd:
    git:
      url: https://github.com/jpnurmi/lxd.dart
      ref: dev
  xterm: #^2.6.0
    git:
      url: https://github.com/jpnurmi/xterm.dart
      ref: flutter-3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
