name: ubuntu_lxd_terminal
description: An experimental Flutter-based LXD terminal UI for Ubuntu.
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  collection: ^1.15.0
  data_size: ^0.2.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0-0
  freezed_annotation: ^2.0.3
  lxd_service:
    path: ../lxd_service
  lxd_store:
    path: ../lxd_store
  lxd_x:
    path: ../lxd_x
  meta: ^1.7.0
  movable_tabs:
    path: ../movable_tabs
  native_context_menu: ^0.2.1+4
  shared_preferences: ^2.0.15
  terminal_view:
    path: ../terminal_view
  ubuntu_service: ^0.1.0
  yaru: ^0.3.0
  yaru_icons: ^0.2.1

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1

dependency_overrides:
  native_context_menu:
    git:
      url: https://github.com/jmatth/native_context_menu.git
      ref: flutter-3

flutter:
  uses-material-design: true
