name: ubuntu_lxd_terminal
description: An experimental Flutter-based LXD terminal UI for Ubuntu.
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  async_value:
    path: ../async_value
  collection: ^1.15.0
  data_size: ^0.2.0
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.0
  freezed_annotation: ^2.0.3
  handy_window: ^0.1.4+1
  lxc_config:
    path: ../lxc_config
  lxd:
    git:
      url: https://github.com/jpnurmi/lxd.dart
      ref: dev
  lxd_service:
    path: ../lxd_service
  lxd_x:
    path: ../lxd_x
  meta: ^1.7.0
  movable_tabs:
    path: ../movable_tabs
  provider: ^6.0.3
  safe_change_notifier: ^0.1.0+1
  shared_preferences: ^2.0.15
  terminal_view:
    path: ../terminal_view
  ubuntu_service: ^0.1.0
  ubuntu_widgets:
    git:
      url: https://github.com/canonical/ubuntu-flutter-plugins.git
      path: packages/ubuntu_widgets
  yaru: ^0.3.0
  yaru_icons: ^0.2.1

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1

flutter:
  uses-material-design: true
  assets:
    - assets/
