name: operating_system_logos
description: OS (Operating System) logos for Flutter.
homepage: https://github.com/EgoistDeveloper/operating-system-logos
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter
  meta: ^1.7.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/src/16x16/
    - assets/src/24x24/
    - assets/src/32x32/
    - assets/src/48x48/
    - assets/src/64x64/
    - assets/src/128x128/
    - assets/src/alpha3-list.json
    - assets/src/os-list.json
