name: lxc_config
description: Interface to lxc config.
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  meta: ^1.7.0
  path: ^1.8.1
  yaml: ^3.1.1

dev_dependencies:
  lints: ^2.0.0
  mockito: ^5.2.0
  test: ^1.16.0
