name: ubuntu-lxd-terminal
version: git
summary: Ubuntu LXD Terminal
description: ...
confinement: strict
base: core22
grade: devel
license: GPL-3.0+
architectures:
  - build-on: amd64

parts:
  flutter-git:
    source: https://github.com/flutter/flutter.git
    source-branch: master
    plugin: nil
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      mkdir -p $CRAFT_PART_INSTALL/usr/libexec
      cp -r $CRAFT_PART_SRC $CRAFT_PART_INSTALL/usr/libexec/flutter
      ln -s $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/flutter $CRAFT_PART_INSTALL/usr/bin/flutter
    build-packages:
      - clang
      - cmake
      - curl
      - ninja-build
      - unzip
      - xz-utils
      - zip
    override-prime: ''

  ubuntu-lxd-terminal:
    after: [ flutter-git ]
    plugin: nil
    source: .
    build-snaps: [ gnome-42-2204-sdk/latest/edge ]
    override-build: |
      set -eux
      cd packages/ubuntu_lxd_terminal
      flutter channel master
      flutter upgrade
      flutter doctor
      flutter pub get
      flutter build linux --release -v
      mkdir -p $CRAFT_PART_INSTALL/bin/
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/bin/

apps:
  ubuntu-lxd-terminal:
    command: bin/ubuntu-lxd-terminal
    desktop: bin/data/flutter_assets/assets/ubuntu-lxd-terminal.desktop
    extensions: [gnome]
    plugs:
      - lxd
      - network
