name: ubuntu-lxd-terminal
version: git
summary: Ubuntu LXD Terminal
description: ...
confinement: strict
base: core20
grade: devel
license: GPL-3.0+
architectures:
  - build-on: amd64

parts:
  flutter-git:
    source: https://github.com/flutter/flutter.git
    source-branch: stable
    source-depth: 1
    plugin: nil
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/libexec
      cp -r $SNAPCRAFT_PART_SRC $SNAPCRAFT_PART_INSTALL/usr/libexec/flutter
      ln -s $SNAPCRAFT_PART_INSTALL/usr/libexec/flutter/bin/flutter $SNAPCRAFT_PART_INSTALL/usr/bin/flutter
    build-packages:
      - clang
      - cmake
      - curl
      - ninja-build
      - unzip
      - xz-utils
      - zip
    override-prime: ''

  ubuntu-lxd-terminal:
    after: [ flutter-git ]
    plugin: nil
    source: .
    override-build: |
      set -eux
      cd packages/ubuntu_lxd_terminal
      flutter pub get
      flutter build linux --release -v
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin/
      cp -r build/linux/*/release/bundle/* $SNAPCRAFT_PART_INSTALL/bin/

apps:
  ubuntu-lxd-terminal:
    command: bin/ubuntu-lxd-terminal
    desktop: bin/data/flutter_assets/assets/ubuntu-lxd-terminal.desktop
    extensions: [gnome-3-38]
    plugs:
      - lxd
