name: lxd_service
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  lxd:
    git:
      url: https://github.com/jpnurmi/lxd.dart
      ref: dev
  lxd_x:
    path: ../lxd_x
  rxdart: ^0.27.3

dev_dependencies:
  build_runner: ^2.1.11
  lints: ^2.0.0
  mockito: ^5.2.0
  test: ^1.16.0
